// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  targetIdentity: __t.identity(),
  adminSecret: __t.string(),
  email: __t.option(__t.string()),
  fullName: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  isPro: __t.option(__t.bool()),
};
