// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  CanDeleteGalleryPhotoResult,
} from "./types";

export const params = {
  s3Key: __t.string(),
  actingAsOrgIdentity: __t.option(__t.identity()),
};
export const returnType = CanDeleteGalleryPhotoResult