// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  profileOwnerIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.option(__t.string()),
  mediaTypes: __t.option(__t.string()),
  actingAsOrgId: __t.option(__t.u64()),
};
