// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.3 (commit 8e410d2842147bd8e5a32a9589cc00c19f7478e2).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendRequestReducer from "./accept_friend_request_reducer";
import AcceptOrgMemberReducer from "./accept_org_member_reducer";
import AddGalleryPhotoReducer from "./add_gallery_photo_reducer";
import AdminDeleteProfileReducer from "./admin_delete_profile_reducer";
import AdminSetBirthdayReducer from "./admin_set_birthday_reducer";
import AdminSetGenderReducer from "./admin_set_gender_reducer";
import AdminSetProReducer from "./admin_set_pro_reducer";
import AdminTransferIdentityReducer from "./admin_transfer_identity_reducer";
import AdminUpdateProfileReducer from "./admin_update_profile_reducer";
import CancelFriendRequestReducer from "./cancel_friend_request_reducer";
import CancelProSubscriptionReducer from "./cancel_pro_subscription_reducer";
import CreateOrganizationReducer from "./create_organization_reducer";
import CreateProfileReducer from "./create_profile_reducer";
import CreateStoryPostReducer from "./create_story_post_reducer";
import DeclineFriendRequestReducer from "./decline_friend_request_reducer";
import DeclineOrgMemberReducer from "./decline_org_member_reducer";
import DeleteGalleryPhotoReducer from "./delete_gallery_photo_reducer";
import DeleteOrganizationReducer from "./delete_organization_reducer";
import DeleteStoryPostReducer from "./delete_story_post_reducer";
import DeliverSearchResultReducer from "./deliver_search_result_reducer";
import DemoteCoLeaderReducer from "./demote_co_leader_reducer";
import EnsureCleanupSweepReducer from "./ensure_cleanup_sweep_reducer";
import FollowReducer from "./follow_reducer";
import JitterOrgToApproxReducer from "./jitter_org_to_approx_reducer";
import JitterToApproxReducer from "./jitter_to_approx_reducer";
import ManualCreateProfileReducer from "./manual_create_profile_reducer";
import PromoteToCoLeaderReducer from "./promote_to_co_leader_reducer";
import RecordOrgClaimFeeReducer from "./record_org_claim_fee_reducer";
import RecordProSubscriptionReducer from "./record_pro_subscription_reducer";
import RefreshFeedReducer from "./refresh_feed_reducer";
import RegisterPushSubscriptionReducer from "./register_push_subscription_reducer";
import RemoveOrgMemberReducer from "./remove_org_member_reducer";
import RequestSemanticSearchReducer from "./request_semantic_search_reducer";
import ResolveNotificationReducer from "./resolve_notification_reducer";
import SendDirectMessageReducer from "./send_direct_message_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SendOrgMemberRequestReducer from "./send_org_member_request_reducer";
import SendOrgMessageReducer from "./send_org_message_reducer";
import SetProfileDisabledReducer from "./set_profile_disabled_reducer";
import TransferLeadershipReducer from "./transfer_leadership_reducer";
import UnfollowReducer from "./unfollow_reducer";
import UnfriendReducer from "./unfriend_reducer";
import UnregisterPushSubscriptionReducer from "./unregister_push_subscription_reducer";
import UpdateFeedScrollPositionReducer from "./update_feed_scroll_position_reducer";
import UpdateLocationReducer from "./update_location_reducer";
import UpdateOrgLocationReducer from "./update_org_location_reducer";
import UpdateOrganizationReducer from "./update_organization_reducer";
import UpdateProfileReducer from "./update_profile_reducer";

// Import all procedure arg schemas
import * as CanDeleteGalleryPhotoProcedure from "./can_delete_gallery_photo_procedure";
import * as CheckDiditVerificationProcedure from "./check_didit_verification_procedure";
import * as CreateVerifiedProfileProcedure from "./create_verified_profile_procedure";
import * as GalleryUploadCountTodayProcedure from "./gallery_upload_count_today_procedure";
import * as GetPendingRegistrationProcedure from "./get_pending_registration_procedure";
import * as GetProfileByEmailProcedure from "./get_profile_by_email_procedure";
import * as GetProfileByIdentityProcedure from "./get_profile_by_identity_procedure";
import * as OauthClaimProfileProcedure from "./oauth_claim_profile_procedure";
import * as RecordPendingRegistrationProcedure from "./record_pending_registration_procedure";
import * as SearchProfilesProcedure from "./search_profiles_procedure";
import * as WhoamiProcedure from "./whoami_procedure";

// Import all table schema definitions
import FollowingRow from "./following_table";
import FriendRequestRow from "./friend_request_table";
import FriendshipRow from "./friendship_table";
import GalleryPhotoRow from "./gallery_photo_table";
import MyFeedRow from "./my_feed_table";
import MyMessagesRow from "./my_messages_table";
import MyNotificationsRow from "./my_notifications_table";
import MyOrgClaimFeeRow from "./my_org_claim_fee_table";
import MyProSubscriptionRow from "./my_pro_subscription_table";
import MySearchAllowanceRow from "./my_search_allowance_table";
import MySearchResultsRow from "./my_search_results_table";
import OrgMemberRequestRow from "./org_member_request_table";
import OrganizationRow from "./organization_table";
import OrganizationMemberRow from "./organization_member_table";
import SearchRequestsForBoxRow from "./search_requests_for_box_table";
import StoryMediaRow from "./story_media_table";
import StoryPostRow from "./story_post_table";
import UserProfileRow from "./user_profile_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  following: __table({
    name: 'following',
    indexes: [
    ],
    constraints: [
    ],
  }, FollowingRow),
  friendRequest: __table({
    name: 'friend_request',
    indexes: [
      { accessor: 'id', name: 'friend_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'friend_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendRequestRow),
  friendship: __table({
    name: 'friendship',
    indexes: [
      { accessor: 'id', name: 'friendship_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'friendship_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendshipRow),
  galleryPhoto: __table({
    name: 'gallery_photo',
    indexes: [
      { accessor: 'created_at', name: 'gallery_photo_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'gallery_photo_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'gallery_photo_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GalleryPhotoRow),
  orgMemberRequest: __table({
    name: 'org_member_request',
    indexes: [
      { accessor: 'id', name: 'org_member_request_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'org_member_request_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrgMemberRequestRow),
  organization: __table({
    name: 'organization',
    indexes: [
      { accessor: 'id', name: 'organization_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'organization_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrganizationRow),
  organizationMember: __table({
    name: 'organization_member',
    indexes: [
    ],
    constraints: [
    ],
  }, OrganizationMemberRow),
  storyMedia: __table({
    name: 'story_media',
    indexes: [
    ],
    constraints: [
    ],
  }, StoryMediaRow),
  storyPost: __table({
    name: 'story_post',
    indexes: [
      { accessor: 'created_at', name: 'story_post_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'story_post_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'story_post_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, StoryPostRow),
  userProfile: __table({
    name: 'user_profile',
    indexes: [
      { accessor: 'email', name: 'user_profile_email_idx_btree', algorithm: 'btree', columns: [
        'email',
      ] },
      { accessor: 'identity', name: 'user_profile_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_profile_email_key', constraint: 'unique', columns: ['email'] },
      { name: 'user_profile_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserProfileRow),
  myFeed: __table({
    name: 'my_feed',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFeedRow),
  myMessages: __table({
    name: 'my_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMessagesRow),
  myNotifications: __table({
    name: 'my_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationsRow),
  myOrgClaimFee: __table({
    name: 'my_org_claim_fee',
    indexes: [
    ],
    constraints: [
    ],
  }, MyOrgClaimFeeRow),
  myProSubscription: __table({
    name: 'my_pro_subscription',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProSubscriptionRow),
  mySearchAllowance: __table({
    name: 'my_search_allowance',
    indexes: [
    ],
    constraints: [
    ],
  }, MySearchAllowanceRow),
  mySearchResults: __table({
    name: 'my_search_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MySearchResultsRow),
  searchRequestsForBox: __table({
    name: 'search_requests_for_box',
    indexes: [
    ],
    constraints: [
    ],
  }, SearchRequestsForBoxRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_friend_request", AcceptFriendRequestReducer),
  __reducerSchema("accept_org_member", AcceptOrgMemberReducer),
  __reducerSchema("add_gallery_photo", AddGalleryPhotoReducer),
  __reducerSchema("admin_delete_profile", AdminDeleteProfileReducer),
  __reducerSchema("admin_set_birthday", AdminSetBirthdayReducer),
  __reducerSchema("admin_set_gender", AdminSetGenderReducer),
  __reducerSchema("admin_set_pro", AdminSetProReducer),
  __reducerSchema("admin_transfer_identity", AdminTransferIdentityReducer),
  __reducerSchema("admin_update_profile", AdminUpdateProfileReducer),
  __reducerSchema("cancel_friend_request", CancelFriendRequestReducer),
  __reducerSchema("cancel_pro_subscription", CancelProSubscriptionReducer),
  __reducerSchema("create_organization", CreateOrganizationReducer),
  __reducerSchema("create_profile", CreateProfileReducer),
  __reducerSchema("create_story_post", CreateStoryPostReducer),
  __reducerSchema("decline_friend_request", DeclineFriendRequestReducer),
  __reducerSchema("decline_org_member", DeclineOrgMemberReducer),
  __reducerSchema("delete_gallery_photo", DeleteGalleryPhotoReducer),
  __reducerSchema("delete_organization", DeleteOrganizationReducer),
  __reducerSchema("delete_story_post", DeleteStoryPostReducer),
  __reducerSchema("deliver_search_result", DeliverSearchResultReducer),
  __reducerSchema("demote_co_leader", DemoteCoLeaderReducer),
  __reducerSchema("ensure_cleanup_sweep", EnsureCleanupSweepReducer),
  __reducerSchema("follow", FollowReducer),
  __reducerSchema("jitter_org_to_approx", JitterOrgToApproxReducer),
  __reducerSchema("jitter_to_approx", JitterToApproxReducer),
  __reducerSchema("manual_create_profile", ManualCreateProfileReducer),
  __reducerSchema("promote_to_co_leader", PromoteToCoLeaderReducer),
  __reducerSchema("record_org_claim_fee", RecordOrgClaimFeeReducer),
  __reducerSchema("record_pro_subscription", RecordProSubscriptionReducer),
  __reducerSchema("refresh_feed", RefreshFeedReducer),
  __reducerSchema("register_push_subscription", RegisterPushSubscriptionReducer),
  __reducerSchema("remove_org_member", RemoveOrgMemberReducer),
  __reducerSchema("request_semantic_search", RequestSemanticSearchReducer),
  __reducerSchema("resolve_notification", ResolveNotificationReducer),
  __reducerSchema("send_direct_message", SendDirectMessageReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("send_org_member_request", SendOrgMemberRequestReducer),
  __reducerSchema("send_org_message", SendOrgMessageReducer),
  __reducerSchema("set_profile_disabled", SetProfileDisabledReducer),
  __reducerSchema("transfer_leadership", TransferLeadershipReducer),
  __reducerSchema("unfollow", UnfollowReducer),
  __reducerSchema("unfriend", UnfriendReducer),
  __reducerSchema("unregister_push_subscription", UnregisterPushSubscriptionReducer),
  __reducerSchema("update_feed_scroll_position", UpdateFeedScrollPositionReducer),
  __reducerSchema("update_location", UpdateLocationReducer),
  __reducerSchema("update_org_location", UpdateOrgLocationReducer),
  __reducerSchema("update_organization", UpdateOrganizationReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("can_delete_gallery_photo", CanDeleteGalleryPhotoProcedure.params, CanDeleteGalleryPhotoProcedure.returnType),
  __procedureSchema("check_didit_verification", CheckDiditVerificationProcedure.params, CheckDiditVerificationProcedure.returnType),
  __procedureSchema("create_verified_profile", CreateVerifiedProfileProcedure.params, CreateVerifiedProfileProcedure.returnType),
  __procedureSchema("gallery_upload_count_today", GalleryUploadCountTodayProcedure.params, GalleryUploadCountTodayProcedure.returnType),
  __procedureSchema("get_pending_registration", GetPendingRegistrationProcedure.params, GetPendingRegistrationProcedure.returnType),
  __procedureSchema("get_profile_by_email", GetProfileByEmailProcedure.params, GetProfileByEmailProcedure.returnType),
  __procedureSchema("get_profile_by_identity", GetProfileByIdentityProcedure.params, GetProfileByIdentityProcedure.returnType),
  __procedureSchema("oauth_claim_profile", OauthClaimProfileProcedure.params, OauthClaimProfileProcedure.returnType),
  __procedureSchema("record_pending_registration", RecordPendingRegistrationProcedure.params, RecordPendingRegistrationProcedure.returnType),
  __procedureSchema("search_profiles", SearchProfilesProcedure.params, SearchProfilesProcedure.returnType),
  __procedureSchema("whoami", WhoamiProcedure.params, WhoamiProcedure.returnType),
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `friendRequest` instead. This alias will be removed in the next major version. */
    readonly "friend_request": Omit<typeof tablesSchema.schemaType.tables["friendRequest"], "accessorName"> & { readonly accessorName: "friend_request" };
    /** @deprecated Use `galleryPhoto` instead. This alias will be removed in the next major version. */
    readonly "gallery_photo": Omit<typeof tablesSchema.schemaType.tables["galleryPhoto"], "accessorName"> & { readonly accessorName: "gallery_photo" };
    /** @deprecated Use `orgMemberRequest` instead. This alias will be removed in the next major version. */
    readonly "org_member_request": Omit<typeof tablesSchema.schemaType.tables["orgMemberRequest"], "accessorName"> & { readonly accessorName: "org_member_request" };
    /** @deprecated Use `organizationMember` instead. This alias will be removed in the next major version. */
    readonly "organization_member": Omit<typeof tablesSchema.schemaType.tables["organizationMember"], "accessorName"> & { readonly accessorName: "organization_member" };
    /** @deprecated Use `storyMedia` instead. This alias will be removed in the next major version. */
    readonly "story_media": Omit<typeof tablesSchema.schemaType.tables["storyMedia"], "accessorName"> & { readonly accessorName: "story_media" };
    /** @deprecated Use `storyPost` instead. This alias will be removed in the next major version. */
    readonly "story_post": Omit<typeof tablesSchema.schemaType.tables["storyPost"], "accessorName"> & { readonly accessorName: "story_post" };
    /** @deprecated Use `userProfile` instead. This alias will be removed in the next major version. */
    readonly "user_profile": Omit<typeof tablesSchema.schemaType.tables["userProfile"], "accessorName"> & { readonly accessorName: "user_profile" };
    /** @deprecated Use `myFeed` instead. This alias will be removed in the next major version. */
    readonly "my_feed": Omit<typeof tablesSchema.schemaType.tables["myFeed"], "accessorName"> & { readonly accessorName: "my_feed" };
    /** @deprecated Use `myMessages` instead. This alias will be removed in the next major version. */
    readonly "my_messages": Omit<typeof tablesSchema.schemaType.tables["myMessages"], "accessorName"> & { readonly accessorName: "my_messages" };
    /** @deprecated Use `myNotifications` instead. This alias will be removed in the next major version. */
    readonly "my_notifications": Omit<typeof tablesSchema.schemaType.tables["myNotifications"], "accessorName"> & { readonly accessorName: "my_notifications" };
    /** @deprecated Use `myOrgClaimFee` instead. This alias will be removed in the next major version. */
    readonly "my_org_claim_fee": Omit<typeof tablesSchema.schemaType.tables["myOrgClaimFee"], "accessorName"> & { readonly accessorName: "my_org_claim_fee" };
    /** @deprecated Use `myProSubscription` instead. This alias will be removed in the next major version. */
    readonly "my_pro_subscription": Omit<typeof tablesSchema.schemaType.tables["myProSubscription"], "accessorName"> & { readonly accessorName: "my_pro_subscription" };
    /** @deprecated Use `mySearchAllowance` instead. This alias will be removed in the next major version. */
    readonly "my_search_allowance": Omit<typeof tablesSchema.schemaType.tables["mySearchAllowance"], "accessorName"> & { readonly accessorName: "my_search_allowance" };
    /** @deprecated Use `mySearchResults` instead. This alias will be removed in the next major version. */
    readonly "my_search_results": Omit<typeof tablesSchema.schemaType.tables["mySearchResults"], "accessorName"> & { readonly accessorName: "my_search_results" };
    /** @deprecated Use `searchRequestsForBox` instead. This alias will be removed in the next major version. */
    readonly "search_requests_for_box": Omit<typeof tablesSchema.schemaType.tables["searchRequestsForBox"], "accessorName"> & { readonly accessorName: "search_requests_for_box" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.3" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "friend_request": "friendRequest",
  "gallery_photo": "galleryPhoto",
  "org_member_request": "orgMemberRequest",
  "organization_member": "organizationMember",
  "story_media": "storyMedia",
  "story_post": "storyPost",
  "user_profile": "userProfile",
  "my_feed": "myFeed",
  "my_messages": "myMessages",
  "my_notifications": "myNotifications",
  "my_org_claim_fee": "myOrgClaimFee",
  "my_pro_subscription": "myProSubscription",
  "my_search_allowance": "mySearchAllowance",
  "my_search_results": "mySearchResults",
  "search_requests_for_box": "searchRequestsForBox",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `friendRequest` instead. This alias will be removed in the next major version. */
  readonly "friend_request": __DbViewBase["friendRequest"];
  /** @deprecated Use `galleryPhoto` instead. This alias will be removed in the next major version. */
  readonly "gallery_photo": __DbViewBase["galleryPhoto"];
  /** @deprecated Use `orgMemberRequest` instead. This alias will be removed in the next major version. */
  readonly "org_member_request": __DbViewBase["orgMemberRequest"];
  /** @deprecated Use `organizationMember` instead. This alias will be removed in the next major version. */
  readonly "organization_member": __DbViewBase["organizationMember"];
  /** @deprecated Use `storyMedia` instead. This alias will be removed in the next major version. */
  readonly "story_media": __DbViewBase["storyMedia"];
  /** @deprecated Use `storyPost` instead. This alias will be removed in the next major version. */
  readonly "story_post": __DbViewBase["storyPost"];
  /** @deprecated Use `userProfile` instead. This alias will be removed in the next major version. */
  readonly "user_profile": __DbViewBase["userProfile"];
  /** @deprecated Use `myFeed` instead. This alias will be removed in the next major version. */
  readonly "my_feed": __DbViewBase["myFeed"];
  /** @deprecated Use `myMessages` instead. This alias will be removed in the next major version. */
  readonly "my_messages": __DbViewBase["myMessages"];
  /** @deprecated Use `myNotifications` instead. This alias will be removed in the next major version. */
  readonly "my_notifications": __DbViewBase["myNotifications"];
  /** @deprecated Use `myOrgClaimFee` instead. This alias will be removed in the next major version. */
  readonly "my_org_claim_fee": __DbViewBase["myOrgClaimFee"];
  /** @deprecated Use `myProSubscription` instead. This alias will be removed in the next major version. */
  readonly "my_pro_subscription": __DbViewBase["myProSubscription"];
  /** @deprecated Use `mySearchAllowance` instead. This alias will be removed in the next major version. */
  readonly "my_search_allowance": __DbViewBase["mySearchAllowance"];
  /** @deprecated Use `mySearchResults` instead. This alias will be removed in the next major version. */
  readonly "my_search_results": __DbViewBase["mySearchResults"];
  /** @deprecated Use `searchRequestsForBox` instead. This alias will be removed in the next major version. */
  readonly "search_requests_for_box": __DbViewBase["searchRequestsForBox"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `friendRequest` instead. This alias will be removed in the next major version. */
  readonly "friend_request": __TablesBase["friendRequest"];
  /** @deprecated Use `galleryPhoto` instead. This alias will be removed in the next major version. */
  readonly "gallery_photo": __TablesBase["galleryPhoto"];
  /** @deprecated Use `orgMemberRequest` instead. This alias will be removed in the next major version. */
  readonly "org_member_request": __TablesBase["orgMemberRequest"];
  /** @deprecated Use `organizationMember` instead. This alias will be removed in the next major version. */
  readonly "organization_member": __TablesBase["organizationMember"];
  /** @deprecated Use `storyMedia` instead. This alias will be removed in the next major version. */
  readonly "story_media": __TablesBase["storyMedia"];
  /** @deprecated Use `storyPost` instead. This alias will be removed in the next major version. */
  readonly "story_post": __TablesBase["storyPost"];
  /** @deprecated Use `userProfile` instead. This alias will be removed in the next major version. */
  readonly "user_profile": __TablesBase["userProfile"];
  /** @deprecated Use `myFeed` instead. This alias will be removed in the next major version. */
  readonly "my_feed": __TablesBase["myFeed"];
  /** @deprecated Use `myMessages` instead. This alias will be removed in the next major version. */
  readonly "my_messages": __TablesBase["myMessages"];
  /** @deprecated Use `myNotifications` instead. This alias will be removed in the next major version. */
  readonly "my_notifications": __TablesBase["myNotifications"];
  /** @deprecated Use `myOrgClaimFee` instead. This alias will be removed in the next major version. */
  readonly "my_org_claim_fee": __TablesBase["myOrgClaimFee"];
  /** @deprecated Use `myProSubscription` instead. This alias will be removed in the next major version. */
  readonly "my_pro_subscription": __TablesBase["myProSubscription"];
  /** @deprecated Use `mySearchAllowance` instead. This alias will be removed in the next major version. */
  readonly "my_search_allowance": __TablesBase["mySearchAllowance"];
  /** @deprecated Use `mySearchResults` instead. This alias will be removed in the next major version. */
  readonly "my_search_results": __TablesBase["mySearchResults"];
  /** @deprecated Use `searchRequestsForBox` instead. This alias will be removed in the next major version. */
  readonly "search_requests_for_box": __TablesBase["searchRequestsForBox"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

