// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  InitiateDiditResult,
} from "./types";

export const params = {
  email: __t.string(),
  profilePicture: __t.string(),
  city: __t.string(),
  description: __t.string(),
  turnstileToken: __t.string(),
};
export const returnType = InitiateDiditResult