// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  senderIdentity: __t.identity().name("sender_identity"),
  recipientIdentity: __t.option(__t.identity()).name("recipient_identity"),
  orgId: __t.option(__t.u64()).name("org_id"),
  content: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
