// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orgId: __t.u64().name("org_id"),
  memberIdentity: __t.identity().name("member_identity"),
  memberName: __t.string().name("member_name"),
  memberPicture: __t.string().name("member_picture"),
  memberCity: __t.string().name("member_city"),
  role: __t.string(),
  joinedAt: __t.timestamp().name("joined_at"),
});
