// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  posterIdentity: __t.identity().name("poster_identity"),
  posterName: __t.string().name("poster_name"),
  posterPicture: __t.string().name("poster_picture"),
  content: __t.string(),
  mediaData: __t.string().name("media_data"),
  mediaTypes: __t.string().name("media_types"),
  mediaUrl: __t.option(__t.string()).name("media_url"),
  createdAt: __t.timestamp().name("created_at"),
  actingAsOrgId: __t.option(__t.u64()).name("acting_as_org_id"),
  actingAsOrgName: __t.option(__t.string()).name("acting_as_org_name"),
  actingAsOrgPicture: __t.option(__t.string()).name("acting_as_org_picture"),
});
