// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  recipientIdentity: __t.identity().name("recipient_identity"),
  type: __t.string(),
  fromIdentity: __t.option(__t.identity()).name("from_identity"),
  orgId: __t.option(__t.u64()).name("org_id"),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  resolved: __t.bool(),
  referenceId: __t.option(__t.u64()).name("reference_id"),
});
