// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  picture: __t.string(),
  city: __t.string(),
  description: __t.string(),
  leaderIdentity: __t.identity().name("leader_identity"),
  createdAt: __t.timestamp().name("created_at"),
  isPro: __t.bool().name("is_pro"),
  locationLat: __t.option(__t.f64()).name("location_lat"),
  locationLng: __t.option(__t.f64()).name("location_lng"),
  locationPrecision: __t.string().name("location_precision"),
  hideMembers: __t.bool().name("hide_members"),
  birthday: __t.option(__t.string()),
  gender: __t.option(__t.string()),
});
