// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SearchProfilesResult,
} from "./types";

export const params = {
  query: __t.string(),
  searchType: __t.string(),
  gender: __t.option(__t.string()),
  ageMin: __t.option(__t.u8()),
  ageMax: __t.option(__t.u8()),
  cursor: __t.option(__t.string()),
  limit: __t.option(__t.u8()),
};
export const returnType = SearchProfilesResult