// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sender: __t.identity(),
  boxId: __t.identity().name("box_id"),
  nonce: __t.string(),
  query: __t.string(),
  paramsJson: __t.string().name("params_json"),
  createdAt: __t.timestamp().name("created_at"),
});
