// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CheckDiditResult = __t.object("CheckDiditResult", {
  success: __t.bool(),
  fullName: __t.option(__t.string()),
  selfieImage: __t.option(__t.string()),
  status: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type CheckDiditResult = __Infer<typeof CheckDiditResult>;

export const CleanupSweep = __t.object("CleanupSweep", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CleanupSweep = __Infer<typeof CleanupSweep>;

export const CreateVerifiedProfileResult = __t.object("CreateVerifiedProfileResult", {
  success: __t.bool(),
  error: __t.option(__t.string()),
});
export type CreateVerifiedProfileResult = __Infer<typeof CreateVerifiedProfileResult>;

export const DiditAttempt = __t.object("DiditAttempt", {
  identity: __t.identity(),
  windowStart: __t.timestamp(),
  attempts: __t.u8(),
});
export type DiditAttempt = __Infer<typeof DiditAttempt>;

export const FeedPosition = __t.object("FeedPosition", {
  identity: __t.identity(),
  lastReadAt: __t.timestamp(),
  lastFeedLoadAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FeedPosition = __Infer<typeof FeedPosition>;

export const FeedStory = __t.object("FeedStory", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
  posterName: __t.string(),
  posterPicture: __t.string(),
  profileOwnerName: __t.string(),
  profileOwnerPicture: __t.string(),
  actingAsOrgId: __t.option(__t.u64()),
  actingAsOrgName: __t.option(__t.string()),
  actingAsOrgPicture: __t.option(__t.string()),
});
export type FeedStory = __Infer<typeof FeedStory>;

export const Following = __t.object("Following", {
  followerIdentity: __t.identity(),
  followingIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Following = __Infer<typeof Following>;

export const FriendRequest = __t.object("FriendRequest", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const Friendship = __t.object("Friendship", {
  id: __t.u64(),
  userA: __t.identity(),
  userB: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const GalleryPhoto = __t.object("GalleryPhoto", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  s3Key: __t.string(),
  url: __t.string(),
  bytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type GalleryPhoto = __Infer<typeof GalleryPhoto>;

export const GalleryUploadCountResult = __t.object("GalleryUploadCountResult", {
  count: __t.u32(),
});
export type GalleryUploadCountResult = __Infer<typeof GalleryUploadCountResult>;

export const LastPost = __t.object("LastPost", {
  posterIdentity: __t.identity(),
  profileOwnerIdentity: __t.identity(),
  lastPostedAt: __t.timestamp(),
});
export type LastPost = __Infer<typeof LastPost>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  senderIdentity: __t.identity(),
  recipientIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const MonthlyVerificationCap = __t.object("MonthlyVerificationCap", {
  monthKey: __t.string(),
  completedCount: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MonthlyVerificationCap = __Infer<typeof MonthlyVerificationCap>;

export const MyFeed = __t.object("MyFeed", {});
export type MyFeed = __Infer<typeof MyFeed>;

export const MyOrgClaimFee = __t.object("MyOrgClaimFee", {});
export type MyOrgClaimFee = __Infer<typeof MyOrgClaimFee>;

export const MyProSubscription = __t.object("MyProSubscription", {});
export type MyProSubscription = __Infer<typeof MyProSubscription>;

export const MySearchAllowance = __t.object("MySearchAllowance", {});
export type MySearchAllowance = __Infer<typeof MySearchAllowance>;

export const MySearchResult = __t.object("MySearchResult", {
  nonce: __t.string(),
  resultsJson: __t.string(),
  reranked: __t.bool(),
});
export type MySearchResult = __Infer<typeof MySearchResult>;

export const MySearchResults = __t.object("MySearchResults", {});
export type MySearchResults = __Infer<typeof MySearchResults>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipientIdentity: __t.identity(),
  type: __t.string(),
  fromIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  message: __t.string(),
  createdAt: __t.timestamp(),
  resolved: __t.bool(),
  referenceId: __t.option(__t.u64()),
});
export type Notification = __Infer<typeof Notification>;

export const OAuthClaimResult = __t.object("OAuthClaimResult", {
  success: __t.bool(),
  alreadyOwned: __t.bool(),
  error: __t.option(__t.string()),
});
export type OAuthClaimResult = __Infer<typeof OAuthClaimResult>;

export const OrgClaimFee = __t.object("OrgClaimFee", {
  identity: __t.identity(),
  amountCents: __t.u32(),
  stripeSessionId: __t.string(),
  paidAt: __t.timestamp(),
  consumed: __t.bool(),
});
export type OrgClaimFee = __Infer<typeof OrgClaimFee>;

export const OrgClaimFeeInfo = __t.object("OrgClaimFeeInfo", {
  amountCents: __t.u32(),
  paidAt: __t.timestamp(),
});
export type OrgClaimFeeInfo = __Infer<typeof OrgClaimFeeInfo>;

export const OrgMemberRequest = __t.object("OrgMemberRequest", {
  id: __t.u64(),
  orgId: __t.u64(),
  fromIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type OrgMemberRequest = __Infer<typeof OrgMemberRequest>;

export const Organization = __t.object("Organization", {
  id: __t.u64(),
  name: __t.string(),
  picture: __t.string(),
  city: __t.string(),
  description: __t.string(),
  leaderIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  isPro: __t.bool(),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.string(),
  hideMembers: __t.bool(),
  birthday: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  pictureSmall: __t.option(__t.string()),
  pictureUrl: __t.option(__t.string()),
});
export type Organization = __Infer<typeof Organization>;

export const OrganizationMember = __t.object("OrganizationMember", {
  orgId: __t.u64(),
  memberIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type OrganizationMember = __Infer<typeof OrganizationMember>;

export const PendingRegistration = __t.object("PendingRegistration", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  legalName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  phoneNumber: __t.string(),
  diditSessionId: __t.string(),
  createdAt: __t.timestamp(),
  profilePicture: __t.string(),
  diditSelfieImage: __t.string(),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
});
export type PendingRegistration = __Infer<typeof PendingRegistration>;

export const PendingRegistrationState = __t.object("PendingRegistrationState", {
  hasPending: __t.bool(),
  verified: __t.bool(),
  legalName: __t.option(__t.string()),
  email: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
});
export type PendingRegistrationState = __Infer<typeof PendingRegistrationState>;

export const PostDailyCount = __t.object("PostDailyCount", {
  identity: __t.identity(),
  day: __t.u32(),
  count: __t.u16(),
});
export type PostDailyCount = __Infer<typeof PostDailyCount>;

export const ProSubscription = __t.object("ProSubscription", {
  identity: __t.identity(),
  amountCents: __t.u32(),
  billingPeriod: __t.string(),
  nextBillDate: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ProSubscription = __Infer<typeof ProSubscription>;

export const ProSubscriptionInfo = __t.object("ProSubscriptionInfo", {
  active: __t.bool(),
  amountCents: __t.u32(),
  billingPeriod: __t.string(),
  nextBillDate: __t.string(),
});
export type ProSubscriptionInfo = __Infer<typeof ProSubscriptionInfo>;

export const ProfileByEmailResult = __t.object("ProfileByEmailResult", {
  found: __t.bool(),
  identityHex: __t.option(__t.string()),
  email: __t.option(__t.string()),
  fullName: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  hideFriends: __t.bool(),
  disabled: __t.bool(),
  createdAtMicros: __t.option(__t.i64()),
  isPro: __t.bool(),
});
export type ProfileByEmailResult = __Infer<typeof ProfileByEmailResult>;

export const ProfileByIdentityResult = __t.object("ProfileByIdentityResult", {
  found: __t.bool(),
  identityHex: __t.option(__t.string()),
  email: __t.option(__t.string()),
  fullName: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  hideFriends: __t.bool(),
  disabled: __t.bool(),
  createdAtMicros: __t.option(__t.i64()),
  isPro: __t.bool(),
});
export type ProfileByIdentityResult = __Infer<typeof ProfileByIdentityResult>;

export const PushSubscription = __t.object("PushSubscription", {
  identity: __t.identity(),
  endpoint: __t.string(),
  p256Dh: __t.string(),
  auth: __t.string(),
  createdAt: __t.timestamp(),
});
export type PushSubscription = __Infer<typeof PushSubscription>;

export const RecordPendingRegistrationResult = __t.object("RecordPendingRegistrationResult", {
  success: __t.bool(),
  error: __t.option(__t.string()),
});
export type RecordPendingRegistrationResult = __Infer<typeof RecordPendingRegistrationResult>;

export const SearchAllowance = __t.object("SearchAllowance", {
  identity: __t.identity(),
  banked: __t.u32(),
  dayKey: __t.string(),
  usedToday: __t.u32(),
  lifetimeUsed: __t.u32(),
  semanticDisabled: __t.bool(),
});
export type SearchAllowance = __Infer<typeof SearchAllowance>;

export const SearchAllowanceInfo = __t.object("SearchAllowanceInfo", {
  banked: __t.u32(),
  usedToday: __t.u32(),
  dayKey: __t.string(),
  disabled: __t.bool(),
});
export type SearchAllowanceInfo = __Infer<typeof SearchAllowanceInfo>;

export const SearchProfilesResult = __t.object("SearchProfilesResult", {
  get results() {
    return __t.array(SearchResultItem);
  },
  nextCursor: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type SearchProfilesResult = __Infer<typeof SearchProfilesResult>;

export const SearchRequest = __t.object("SearchRequest", {
  sender: __t.identity(),
  boxId: __t.identity(),
  nonce: __t.string(),
  query: __t.string(),
  paramsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SearchRequest = __Infer<typeof SearchRequest>;

export const SearchRequestForBox = __t.object("SearchRequestForBox", {
  nonce: __t.string(),
  query: __t.string(),
  paramsJson: __t.string(),
});
export type SearchRequestForBox = __Infer<typeof SearchRequestForBox>;

export const SearchRequestsForBox = __t.object("SearchRequestsForBox", {});
export type SearchRequestsForBox = __Infer<typeof SearchRequestsForBox>;

export const SearchResult = __t.object("SearchResult", {
  recipient: __t.identity(),
  boxId: __t.identity(),
  nonce: __t.string(),
  resultsJson: __t.string(),
  reranked: __t.bool(),
  createdAt: __t.timestamp(),
});
export type SearchResult = __Infer<typeof SearchResult>;

export const SearchResultItem = __t.object("SearchResultItem", {
  resultType: __t.string(),
  identityHex: __t.string(),
  orgId: __t.option(__t.u64()),
  email: __t.string(),
  fullName: __t.string(),
  profilePicture: __t.string(),
  profilePictureSmall: __t.string(),
  profilePictureUrl: __t.string(),
  city: __t.string(),
  description: __t.string(),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
});
export type SearchResultItem = __Infer<typeof SearchResultItem>;

export const StoryPost = __t.object("StoryPost", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
  actingAsOrgId: __t.option(__t.u64()),
});
export type StoryPost = __Infer<typeof StoryPost>;

export const UserBirthday = __t.object("UserBirthday", {
  identity: __t.identity(),
  birthday: __t.string(),
});
export type UserBirthday = __Infer<typeof UserBirthday>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  createdAt: __t.timestamp(),
  phoneNumber: __t.string(),
  phoneVerified: __t.bool(),
  profilePicture: __t.string(),
  isPro: __t.bool(),
  manuallyCreated: __t.bool(),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.string(),
  locationAsked: __t.bool(),
  hideFriends: __t.bool(),
  birthday: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  disabled: __t.bool(),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const VerificationRateLimit = __t.object("VerificationRateLimit", {
  identity: __t.identity(),
  attemptCount: __t.u32(),
  lastAttemptAt: __t.timestamp(),
  firstAttemptAt: __t.timestamp(),
});
export type VerificationRateLimit = __Infer<typeof VerificationRateLimit>;

export const VerifiedIdentity = __t.object("VerifiedIdentity", {
  identity: __t.identity(),
  legalName: __t.string(),
  diditVerified: __t.bool(),
  diditSelfieImage: __t.string(),
});
export type VerifiedIdentity = __Infer<typeof VerifiedIdentity>;

export const WhoAmIResult = __t.object("WhoAmIResult", {
  identityHex: __t.string(),
  authenticated: __t.bool(),
});
export type WhoAmIResult = __Infer<typeof WhoAmIResult>;

