// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CanDeleteGalleryPhotoResult = __t.object("CanDeleteGalleryPhotoResult", {
  allowed: __t.bool(),
});
export type CanDeleteGalleryPhotoResult = __Infer<typeof CanDeleteGalleryPhotoResult>;

export const CheckDiditResult = __t.object("CheckDiditResult", {
  success: __t.bool(),
  fullName: __t.option(__t.string()),
  selfieImage: __t.option(__t.string()),
  status: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type CheckDiditResult = __Infer<typeof CheckDiditResult>;

export const CleanupSweep = __t.object("CleanupSweep", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CleanupSweep = __Infer<typeof CleanupSweep>;

export const CreateVerifiedProfileResult = __t.object("CreateVerifiedProfileResult", {
  success: __t.bool(),
  error: __t.option(__t.string()),
});
export type CreateVerifiedProfileResult = __Infer<typeof CreateVerifiedProfileResult>;

export const DiditAttempt = __t.object("DiditAttempt", {
  identity: __t.identity(),
  windowStart: __t.timestamp(),
  attempts: __t.u8(),
});
export type DiditAttempt = __Infer<typeof DiditAttempt>;

export const FeedPosition = __t.object("FeedPosition", {
  identity: __t.identity(),
  lastReadAt: __t.timestamp(),
  lastFeedLoadAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FeedPosition = __Infer<typeof FeedPosition>;

export const FeedStory = __t.object("FeedStory", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  mediaUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  posterName: __t.string(),
  posterPicture: __t.string(),
  profileOwnerName: __t.string(),
  profileOwnerPicture: __t.string(),
  actingAsOrgId: __t.option(__t.u64()),
  actingAsOrgName: __t.option(__t.string()),
  actingAsOrgPicture: __t.option(__t.string()),
});
export type FeedStory = __Infer<typeof FeedStory>;

export const Following = __t.object("Following", {
  followerIdentity: __t.identity(),
  followingIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Following = __Infer<typeof Following>;

export const FriendRequest = __t.object("FriendRequest", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type FriendRequest = __Infer<typeof FriendRequest>;

export const FriendResultItem = __t.object("FriendResultItem", {
  identityHex: __t.string(),
  fullName: __t.string(),
  picture: __t.string(),
  city: __t.string(),
});
export type FriendResultItem = __Infer<typeof FriendResultItem>;

export const Friendship = __t.object("Friendship", {
  id: __t.u64(),
  userA: __t.identity(),
  userB: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const GalleryPhoto = __t.object("GalleryPhoto", {
  id: __t.u64(),
  ownerIdentity: __t.identity(),
  s3Key: __t.string(),
  url: __t.string(),
  bytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type GalleryPhoto = __Infer<typeof GalleryPhoto>;

export const GalleryResultItem = __t.object("GalleryResultItem", {
  id: __t.u64(),
  s3Key: __t.string(),
  url: __t.string(),
  bytes: __t.u64(),
  createdAtMicros: __t.u64(),
});
export type GalleryResultItem = __Infer<typeof GalleryResultItem>;

export const GalleryUploadCountResult = __t.object("GalleryUploadCountResult", {
  count: __t.u32(),
});
export type GalleryUploadCountResult = __Infer<typeof GalleryUploadCountResult>;

export const GetOrgMembersResult = __t.object("GetOrgMembersResult", {
  get members() {
    return __t.array(OrgMemberResultItem);
  },
});
export type GetOrgMembersResult = __Infer<typeof GetOrgMembersResult>;

export const GetOrgProfileResult = __t.object("GetOrgProfileResult", {
  found: __t.bool(),
  orgId: __t.option(__t.u64()),
  name: __t.option(__t.string()),
  picture: __t.option(__t.string()),
  pictureSmall: __t.option(__t.string()),
  pictureUrl: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  createdAtMicros: __t.option(__t.u64()),
  gender: __t.option(__t.string()),
  hideMembers: __t.option(__t.bool()),
  isPro: __t.option(__t.bool()),
  leaderIdentityHex: __t.option(__t.string()),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.option(__t.string()),
});
export type GetOrgProfileResult = __Infer<typeof GetOrgProfileResult>;

export const GetProfileFriendsResult = __t.object("GetProfileFriendsResult", {
  get friends() {
    return __t.array(FriendResultItem);
  },
});
export type GetProfileFriendsResult = __Infer<typeof GetProfileFriendsResult>;

export const GetProfileGalleryResult = __t.object("GetProfileGalleryResult", {
  get photos() {
    return __t.array(GalleryResultItem);
  },
});
export type GetProfileGalleryResult = __Infer<typeof GetProfileGalleryResult>;

export const GetProfileStoriesResult = __t.object("GetProfileStoriesResult", {
  get stories() {
    return __t.array(StoryResultItem);
  },
});
export type GetProfileStoriesResult = __Infer<typeof GetProfileStoriesResult>;

export const LastPost = __t.object("LastPost", {
  posterIdentity: __t.identity(),
  profileOwnerIdentity: __t.identity(),
  lastPostedAt: __t.timestamp(),
});
export type LastPost = __Infer<typeof LastPost>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  senderIdentity: __t.identity(),
  recipientIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const MonthlyVerificationCap = __t.object("MonthlyVerificationCap", {
  monthKey: __t.string(),
  completedCount: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MonthlyVerificationCap = __Infer<typeof MonthlyVerificationCap>;

export const MyFeed = __t.object("MyFeed", {});
export type MyFeed = __Infer<typeof MyFeed>;

export const MyFollowEdge = __t.object("MyFollowEdge", {
  followingIdentity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type MyFollowEdge = __Infer<typeof MyFollowEdge>;

export const MyFollowing = __t.object("MyFollowing", {});
export type MyFollowing = __Infer<typeof MyFollowing>;

export const MyFriend = __t.object("MyFriend", {
  friendIdentity: __t.identity(),
  friendName: __t.string(),
  friendPicture: __t.string(),
  friendCity: __t.string(),
  createdAt: __t.timestamp(),
});
export type MyFriend = __Infer<typeof MyFriend>;

export const MyFriendRequest = __t.object("MyFriendRequest", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  fromName: __t.string(),
  fromPicture: __t.string(),
});
export type MyFriendRequest = __Infer<typeof MyFriendRequest>;

export const MyFriendRequests = __t.object("MyFriendRequests", {});
export type MyFriendRequests = __Infer<typeof MyFriendRequests>;

export const MyFriendships = __t.object("MyFriendships", {});
export type MyFriendships = __Infer<typeof MyFriendships>;

export const MyGallery = __t.object("MyGallery", {});
export type MyGallery = __Infer<typeof MyGallery>;

export const MyGalleryPhoto = __t.object("MyGalleryPhoto", {
  id: __t.u64(),
  s3Key: __t.string(),
  url: __t.string(),
  bytes: __t.u64(),
  createdAt: __t.timestamp(),
});
export type MyGalleryPhoto = __Infer<typeof MyGalleryPhoto>;

export const MyMessage = __t.object("MyMessage", {
  id: __t.u64(),
  senderIdentity: __t.identity(),
  recipientIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  content: __t.string(),
  createdAt: __t.timestamp(),
});
export type MyMessage = __Infer<typeof MyMessage>;

export const MyMessages = __t.object("MyMessages", {});
export type MyMessages = __Infer<typeof MyMessages>;

export const MyNotification = __t.object("MyNotification", {
  id: __t.u64(),
  recipientIdentity: __t.identity(),
  type: __t.string(),
  fromIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  message: __t.string(),
  createdAt: __t.timestamp(),
  resolved: __t.bool(),
  referenceId: __t.option(__t.u64()),
});
export type MyNotification = __Infer<typeof MyNotification>;

export const MyNotifications = __t.object("MyNotifications", {});
export type MyNotifications = __Infer<typeof MyNotifications>;

export const MyOrg = __t.object("MyOrg", {
  orgId: __t.u64(),
  name: __t.string(),
  picture: __t.string(),
  pictureSmall: __t.option(__t.string()),
  pictureUrl: __t.option(__t.string()),
  city: __t.string(),
  description: __t.string(),
  gender: __t.option(__t.string()),
  hideMembers: __t.bool(),
  leaderIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  isPro: __t.bool(),
  myRole: __t.string(),
});
export type MyOrg = __Infer<typeof MyOrg>;

export const MyOrgClaimFee = __t.object("MyOrgClaimFee", {});
export type MyOrgClaimFee = __Infer<typeof MyOrgClaimFee>;

export const MyOrgMember = __t.object("MyOrgMember", {
  orgId: __t.u64(),
  memberIdentity: __t.identity(),
  memberName: __t.string(),
  memberPicture: __t.string(),
  memberCity: __t.string(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type MyOrgMember = __Infer<typeof MyOrgMember>;

export const MyOrgMembers = __t.object("MyOrgMembers", {});
export type MyOrgMembers = __Infer<typeof MyOrgMembers>;

export const MyOrgRequest = __t.object("MyOrgRequest", {
  id: __t.u64(),
  orgId: __t.u64(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type MyOrgRequest = __Infer<typeof MyOrgRequest>;

export const MyOrgRequests = __t.object("MyOrgRequests", {});
export type MyOrgRequests = __Infer<typeof MyOrgRequests>;

export const MyOrgs = __t.object("MyOrgs", {});
export type MyOrgs = __Infer<typeof MyOrgs>;

export const MyOwnProfile = __t.object("MyOwnProfile", {});
export type MyOwnProfile = __Infer<typeof MyOwnProfile>;

export const MyPost = __t.object("MyPost", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  profileOwnerName: __t.string(),
  profileOwnerPicture: __t.string(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  mediaUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  actingAsOrgId: __t.option(__t.u64()),
});
export type MyPost = __Infer<typeof MyPost>;

export const MyPosts = __t.object("MyPosts", {});
export type MyPosts = __Infer<typeof MyPosts>;

export const MyProSubscription = __t.object("MyProSubscription", {});
export type MyProSubscription = __Infer<typeof MyProSubscription>;

export const MySearchAllowance = __t.object("MySearchAllowance", {});
export type MySearchAllowance = __Infer<typeof MySearchAllowance>;

export const MySearchResult = __t.object("MySearchResult", {
  nonce: __t.string(),
  resultsJson: __t.string(),
  reranked: __t.bool(),
});
export type MySearchResult = __Infer<typeof MySearchResult>;

export const MySearchResults = __t.object("MySearchResults", {});
export type MySearchResults = __Infer<typeof MySearchResults>;

export const MyStory = __t.object("MyStory", {});
export type MyStory = __Infer<typeof MyStory>;

export const MyStoryPost = __t.object("MyStoryPost", {
  id: __t.u64(),
  posterIdentity: __t.identity(),
  posterName: __t.string(),
  posterPicture: __t.string(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  mediaUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  actingAsOrgId: __t.option(__t.u64()),
  actingAsOrgName: __t.option(__t.string()),
  actingAsOrgPicture: __t.option(__t.string()),
});
export type MyStoryPost = __Infer<typeof MyStoryPost>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  recipientIdentity: __t.identity(),
  type: __t.string(),
  fromIdentity: __t.option(__t.identity()),
  orgId: __t.option(__t.u64()),
  message: __t.string(),
  createdAt: __t.timestamp(),
  resolved: __t.bool(),
  referenceId: __t.option(__t.u64()),
});
export type Notification = __Infer<typeof Notification>;

export const OAuthClaimResult = __t.object("OAuthClaimResult", {
  success: __t.bool(),
  alreadyOwned: __t.bool(),
  error: __t.option(__t.string()),
});
export type OAuthClaimResult = __Infer<typeof OAuthClaimResult>;

export const OrgClaimFee = __t.object("OrgClaimFee", {
  identity: __t.identity(),
  amountCents: __t.u32(),
  stripeSessionId: __t.string(),
  paidAt: __t.timestamp(),
  consumed: __t.bool(),
});
export type OrgClaimFee = __Infer<typeof OrgClaimFee>;

export const OrgClaimFeeInfo = __t.object("OrgClaimFeeInfo", {
  amountCents: __t.u32(),
  paidAt: __t.timestamp(),
});
export type OrgClaimFeeInfo = __Infer<typeof OrgClaimFeeInfo>;

export const OrgMemberRequest = __t.object("OrgMemberRequest", {
  id: __t.u64(),
  orgId: __t.u64(),
  fromIdentity: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type OrgMemberRequest = __Infer<typeof OrgMemberRequest>;

export const OrgMemberResultItem = __t.object("OrgMemberResultItem", {
  identityHex: __t.string(),
  fullName: __t.string(),
  picture: __t.string(),
  city: __t.string(),
  role: __t.string(),
});
export type OrgMemberResultItem = __Infer<typeof OrgMemberResultItem>;

export const Organization = __t.object("Organization", {
  id: __t.u64(),
  name: __t.string(),
  picture: __t.string(),
  city: __t.string(),
  description: __t.string(),
  leaderIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  isPro: __t.bool(),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.string(),
  hideMembers: __t.bool(),
  birthday: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  pictureSmall: __t.option(__t.string()),
  pictureUrl: __t.option(__t.string()),
});
export type Organization = __Infer<typeof Organization>;

export const OrganizationMember = __t.object("OrganizationMember", {
  orgId: __t.u64(),
  memberIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
});
export type OrganizationMember = __Infer<typeof OrganizationMember>;

export const OwnProfileData = __t.object("OwnProfileData", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  createdAt: __t.timestamp(),
  profilePicture: __t.string(),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.string(),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  hideFriends: __t.bool(),
  disabled: __t.bool(),
  isPro: __t.bool(),
});
export type OwnProfileData = __Infer<typeof OwnProfileData>;

export const PendingRegistration = __t.object("PendingRegistration", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  legalName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  phoneNumber: __t.string(),
  diditSessionId: __t.string(),
  createdAt: __t.timestamp(),
  profilePicture: __t.string(),
  diditSelfieImage: __t.string(),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
});
export type PendingRegistration = __Infer<typeof PendingRegistration>;

export const PendingRegistrationState = __t.object("PendingRegistrationState", {
  hasPending: __t.bool(),
  verified: __t.bool(),
  legalName: __t.option(__t.string()),
  email: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
});
export type PendingRegistrationState = __Infer<typeof PendingRegistrationState>;

export const PostDailyCount = __t.object("PostDailyCount", {
  identity: __t.identity(),
  day: __t.u32(),
  count: __t.u16(),
});
export type PostDailyCount = __Infer<typeof PostDailyCount>;

export const ProSubscription = __t.object("ProSubscription", {
  identity: __t.identity(),
  amountCents: __t.u32(),
  billingPeriod: __t.string(),
  nextBillDate: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ProSubscription = __Infer<typeof ProSubscription>;

export const ProSubscriptionInfo = __t.object("ProSubscriptionInfo", {
  active: __t.bool(),
  amountCents: __t.u32(),
  billingPeriod: __t.string(),
  nextBillDate: __t.string(),
});
export type ProSubscriptionInfo = __Infer<typeof ProSubscriptionInfo>;

export const ProfileByEmailResult = __t.object("ProfileByEmailResult", {
  found: __t.bool(),
  identityHex: __t.option(__t.string()),
  email: __t.option(__t.string()),
  fullName: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  hideFriends: __t.bool(),
  disabled: __t.bool(),
  createdAtMicros: __t.option(__t.i64()),
  isPro: __t.bool(),
});
export type ProfileByEmailResult = __Infer<typeof ProfileByEmailResult>;

export const ProfileByIdentityResult = __t.object("ProfileByIdentityResult", {
  found: __t.bool(),
  identityHex: __t.option(__t.string()),
  email: __t.option(__t.string()),
  fullName: __t.option(__t.string()),
  city: __t.option(__t.string()),
  description: __t.option(__t.string()),
  profilePicture: __t.option(__t.string()),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  hideFriends: __t.bool(),
  disabled: __t.bool(),
  createdAtMicros: __t.option(__t.i64()),
  isPro: __t.bool(),
});
export type ProfileByIdentityResult = __Infer<typeof ProfileByIdentityResult>;

export const PushSubscription = __t.object("PushSubscription", {
  identity: __t.identity(),
  endpoint: __t.string(),
  p256Dh: __t.string(),
  auth: __t.string(),
  createdAt: __t.timestamp(),
});
export type PushSubscription = __Infer<typeof PushSubscription>;

export const RecordPendingRegistrationResult = __t.object("RecordPendingRegistrationResult", {
  success: __t.bool(),
  error: __t.option(__t.string()),
});
export type RecordPendingRegistrationResult = __Infer<typeof RecordPendingRegistrationResult>;

export const SearchAllowance = __t.object("SearchAllowance", {
  identity: __t.identity(),
  banked: __t.u32(),
  dayKey: __t.string(),
  usedToday: __t.u32(),
  lifetimeUsed: __t.u32(),
  semanticDisabled: __t.bool(),
});
export type SearchAllowance = __Infer<typeof SearchAllowance>;

export const SearchAllowanceInfo = __t.object("SearchAllowanceInfo", {
  banked: __t.u32(),
  usedToday: __t.u32(),
  dayKey: __t.string(),
  disabled: __t.bool(),
});
export type SearchAllowanceInfo = __Infer<typeof SearchAllowanceInfo>;

export const SearchProfilesResult = __t.object("SearchProfilesResult", {
  get results() {
    return __t.array(SearchResultItem);
  },
  nextCursor: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type SearchProfilesResult = __Infer<typeof SearchProfilesResult>;

export const SearchRequest = __t.object("SearchRequest", {
  sender: __t.identity(),
  boxId: __t.identity(),
  nonce: __t.string(),
  query: __t.string(),
  paramsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SearchRequest = __Infer<typeof SearchRequest>;

export const SearchRequestForBox = __t.object("SearchRequestForBox", {
  nonce: __t.string(),
  query: __t.string(),
  paramsJson: __t.string(),
});
export type SearchRequestForBox = __Infer<typeof SearchRequestForBox>;

export const SearchRequestsForBox = __t.object("SearchRequestsForBox", {});
export type SearchRequestsForBox = __Infer<typeof SearchRequestsForBox>;

export const SearchResult = __t.object("SearchResult", {
  recipient: __t.identity(),
  boxId: __t.identity(),
  nonce: __t.string(),
  resultsJson: __t.string(),
  reranked: __t.bool(),
  createdAt: __t.timestamp(),
});
export type SearchResult = __Infer<typeof SearchResult>;

export const SearchResultItem = __t.object("SearchResultItem", {
  resultType: __t.string(),
  identityHex: __t.string(),
  orgId: __t.option(__t.u64()),
  email: __t.string(),
  fullName: __t.string(),
  profilePicture: __t.string(),
  profilePictureSmall: __t.string(),
  profilePictureUrl: __t.string(),
  city: __t.string(),
  description: __t.string(),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
});
export type SearchResultItem = __Infer<typeof SearchResultItem>;

export const StoryMedia = __t.object("StoryMedia", {
  posterIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  mediaKey: __t.string(),
  mediaUrl: __t.string(),
  mediaBytes: __t.u64(),
  mediaType: __t.string(),
});
export type StoryMedia = __Infer<typeof StoryMedia>;

export const StoryPost = __t.object("StoryPost", {
  id: __t.u64(),
  profileOwnerIdentity: __t.identity(),
  posterIdentity: __t.identity(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  createdAt: __t.timestamp(),
  actingAsOrgId: __t.option(__t.u64()),
});
export type StoryPost = __Infer<typeof StoryPost>;

export const StoryResultItem = __t.object("StoryResultItem", {
  id: __t.u64(),
  posterIdentityHex: __t.string(),
  posterName: __t.string(),
  posterPicture: __t.string(),
  content: __t.string(),
  mediaData: __t.string(),
  mediaTypes: __t.string(),
  mediaUrl: __t.option(__t.string()),
  createdAtMicros: __t.u64(),
  actingAsOrgId: __t.option(__t.u64()),
  actingAsOrgName: __t.option(__t.string()),
  actingAsOrgPicture: __t.option(__t.string()),
});
export type StoryResultItem = __Infer<typeof StoryResultItem>;

export const UserBirthday = __t.object("UserBirthday", {
  identity: __t.identity(),
  birthday: __t.string(),
});
export type UserBirthday = __Infer<typeof UserBirthday>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  email: __t.string(),
  fullName: __t.string(),
  city: __t.string(),
  description: __t.string(),
  createdAt: __t.timestamp(),
  phoneNumber: __t.string(),
  phoneVerified: __t.bool(),
  profilePicture: __t.string(),
  isPro: __t.bool(),
  manuallyCreated: __t.bool(),
  locationLat: __t.option(__t.f64()),
  locationLng: __t.option(__t.f64()),
  locationPrecision: __t.string(),
  locationAsked: __t.bool(),
  hideFriends: __t.bool(),
  birthday: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
  disabled: __t.bool(),
  profilePictureSmall: __t.option(__t.string()),
  profilePictureUrl: __t.option(__t.string()),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const VerificationRateLimit = __t.object("VerificationRateLimit", {
  identity: __t.identity(),
  attemptCount: __t.u32(),
  lastAttemptAt: __t.timestamp(),
  firstAttemptAt: __t.timestamp(),
});
export type VerificationRateLimit = __Infer<typeof VerificationRateLimit>;

export const VerifiedIdentity = __t.object("VerifiedIdentity", {
  identity: __t.identity(),
  legalName: __t.string(),
  diditVerified: __t.bool(),
  diditSelfieImage: __t.string(),
});
export type VerifiedIdentity = __Infer<typeof VerifiedIdentity>;

export const WhoAmIResult = __t.object("WhoAmIResult", {
  identityHex: __t.string(),
  authenticated: __t.bool(),
});
export type WhoAmIResult = __Infer<typeof WhoAmIResult>;

