// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  email: __t.string(),
  fullName: __t.string().name("full_name"),
  city: __t.string(),
  description: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  phoneNumber: __t.string().name("phone_number"),
  phoneVerified: __t.bool().name("phone_verified"),
  profilePicture: __t.string().name("profile_picture"),
  isPro: __t.bool().name("is_pro"),
  manuallyCreated: __t.bool().name("manually_created"),
  locationLat: __t.option(__t.f64()).name("location_lat"),
  locationLng: __t.option(__t.f64()).name("location_lng"),
  locationPrecision: __t.string().name("location_precision"),
  locationAsked: __t.bool().name("location_asked"),
  hideFriends: __t.bool().name("hide_friends"),
  birthday: __t.option(__t.string()),
  gender: __t.option(__t.string()),
  age: __t.option(__t.u8()),
});
