// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CanDeleteGalleryPhotoProcedure from "../can_delete_gallery_photo_procedure";
import * as CheckDiditVerificationProcedure from "../check_didit_verification_procedure";
import * as CreateVerifiedProfileProcedure from "../create_verified_profile_procedure";
import * as GalleryUploadCountTodayProcedure from "../gallery_upload_count_today_procedure";
import * as GetOrgMembersProcedure from "../get_org_members_procedure";
import * as GetOrgProfileProcedure from "../get_org_profile_procedure";
import * as GetPendingRegistrationProcedure from "../get_pending_registration_procedure";
import * as GetProfileByEmailProcedure from "../get_profile_by_email_procedure";
import * as GetProfileByIdentityProcedure from "../get_profile_by_identity_procedure";
import * as GetProfileFriendsProcedure from "../get_profile_friends_procedure";
import * as GetProfileGalleryProcedure from "../get_profile_gallery_procedure";
import * as GetProfileStoriesProcedure from "../get_profile_stories_procedure";
import * as OauthClaimProfileProcedure from "../oauth_claim_profile_procedure";
import * as RecordPendingRegistrationProcedure from "../record_pending_registration_procedure";
import * as SearchProfilesProcedure from "../search_profiles_procedure";
import * as WhoamiProcedure from "../whoami_procedure";

export type CanDeleteGalleryPhotoArgs = __Infer<typeof CanDeleteGalleryPhotoProcedure.params>;
export type CanDeleteGalleryPhotoResult = __Infer<typeof CanDeleteGalleryPhotoProcedure.returnType>;
export type CheckDiditVerificationArgs = __Infer<typeof CheckDiditVerificationProcedure.params>;
export type CheckDiditVerificationResult = __Infer<typeof CheckDiditVerificationProcedure.returnType>;
export type CreateVerifiedProfileArgs = __Infer<typeof CreateVerifiedProfileProcedure.params>;
export type CreateVerifiedProfileResult = __Infer<typeof CreateVerifiedProfileProcedure.returnType>;
export type GalleryUploadCountTodayArgs = __Infer<typeof GalleryUploadCountTodayProcedure.params>;
export type GalleryUploadCountTodayResult = __Infer<typeof GalleryUploadCountTodayProcedure.returnType>;
export type GetOrgMembersArgs = __Infer<typeof GetOrgMembersProcedure.params>;
export type GetOrgMembersResult = __Infer<typeof GetOrgMembersProcedure.returnType>;
export type GetOrgProfileArgs = __Infer<typeof GetOrgProfileProcedure.params>;
export type GetOrgProfileResult = __Infer<typeof GetOrgProfileProcedure.returnType>;
export type GetPendingRegistrationArgs = __Infer<typeof GetPendingRegistrationProcedure.params>;
export type GetPendingRegistrationResult = __Infer<typeof GetPendingRegistrationProcedure.returnType>;
export type GetProfileByEmailArgs = __Infer<typeof GetProfileByEmailProcedure.params>;
export type GetProfileByEmailResult = __Infer<typeof GetProfileByEmailProcedure.returnType>;
export type GetProfileByIdentityArgs = __Infer<typeof GetProfileByIdentityProcedure.params>;
export type GetProfileByIdentityResult = __Infer<typeof GetProfileByIdentityProcedure.returnType>;
export type GetProfileFriendsArgs = __Infer<typeof GetProfileFriendsProcedure.params>;
export type GetProfileFriendsResult = __Infer<typeof GetProfileFriendsProcedure.returnType>;
export type GetProfileGalleryArgs = __Infer<typeof GetProfileGalleryProcedure.params>;
export type GetProfileGalleryResult = __Infer<typeof GetProfileGalleryProcedure.returnType>;
export type GetProfileStoriesArgs = __Infer<typeof GetProfileStoriesProcedure.params>;
export type GetProfileStoriesResult = __Infer<typeof GetProfileStoriesProcedure.returnType>;
export type OauthClaimProfileArgs = __Infer<typeof OauthClaimProfileProcedure.params>;
export type OauthClaimProfileResult = __Infer<typeof OauthClaimProfileProcedure.returnType>;
export type RecordPendingRegistrationArgs = __Infer<typeof RecordPendingRegistrationProcedure.params>;
export type RecordPendingRegistrationResult = __Infer<typeof RecordPendingRegistrationProcedure.returnType>;
export type SearchProfilesArgs = __Infer<typeof SearchProfilesProcedure.params>;
export type SearchProfilesResult = __Infer<typeof SearchProfilesProcedure.returnType>;
export type WhoamiArgs = __Infer<typeof WhoamiProcedure.params>;
export type WhoamiResult = __Infer<typeof WhoamiProcedure.returnType>;

